import React,{useEffect,useMemo,useState} from 'react';
import {BarChart3,ShoppingBag,UserRound,CheckCircle2,RefreshCw,LockKeyhole} from 'lucide-react';
import {backendReady,getSession,listProducts,listMyProducts,listMyOrders,createPendingOrder,upsertCustomerProfile,listRsvpAnalytics} from './lib/supabase';

export default function SaaSPanel({onBack}){
 const [products,setProducts]=useState([]),[owned,setOwned]=useState([]),[orders,setOrders]=useState([]),[analytics,setAnalytics]=useState([]),[profile,setProfile]=useState({full_name:'',phone:'',country:''}),[loading,setLoading]=useState(true),[message,setMessage]=useState('');
 const user=getSession()?.user;
 useEffect(()=>{let live=true;(async()=>{if(!backendReady()){setLoading(false);return;}try{const p=await listProducts();if(!live)return;setProducts(p||[]);if(user){const [o,ord,a]=await Promise.all([listMyProducts(),listMyOrders(),listRsvpAnalytics()]);if(!live)return;setOwned(o||[]);setOrders(ord||[]);setAnalytics(a||[]);setProfile(x=>({...x,full_name:user.user_metadata?.full_name||user.email?.split('@')[0]||''}));}}catch(e){if(live)setMessage(e.message||'Unable to load the store.')}finally{if(live)setLoading(false)}})();return()=>{live=false}},[]);
 const totals=useMemo(()=>analytics.reduce((a,r)=>({responses:a.responses+Number(r.total_responses||0),attending:a.attending+Number(r.attending_responses||0),guests:a.guests+Number(r.attending_guests||0)}),{responses:0,attending:0,guests:0}),[analytics]);
 const ownedIds=new Set(owned.map(x=>x.product_id));
 async function buy(product){if(!user){window.location.hash='login';return}try{const order=await createPendingOrder(product.id);setOrders(o=>[order,...o]);setMessage(`تم إنشاء طلب ${product.name} بقيمة AED ${Number(product.price_aed||0)}. سيتم إكمال الدفع في خطوة الدفع.`)}catch(e){setMessage(e.message||'تعذر إنشاء الطلب.')}}
 async function saveProfile(e){e.preventDefault();if(!user){window.location.hash='login';return}try{await upsertCustomerProfile(profile);setMessage('تم حفظ بيانات الحساب بنجاح.')}catch(e){setMessage(e.message||'تعذر حفظ البيانات.')}}
 return <div className="saas-panel"><div className="saas-head"><div><div className="eyebrow">EVERLY STORE</div><h2>متجر الدعوات والقوالب</h2><p>{user?.email||'متجر Everly'} · شراء لمرة واحدة، بدون اشتراك شهري.</p></div><button className="ghost-button" onClick={onBack}>رجوع</button></div>
 {message&&<div className="saas-message">{message}</div>}
 <section className="saas-grid"><div className="saas-card"><div className="card-icon"><ShoppingBag size={19}/></div><h3>منتجاتي</h3><strong>{owned.length}</strong><p>{user?'دعوات وقوالب تم شراؤها.':'سجّل الدخول لمشاهدة مشترياتك.'}</p></div><div className="saas-card"><div className="card-icon"><BarChart3 size={19}/></div><h3>RSVP</h3><div className="mini-stats"><span><b>{totals.responses}</b> ردود</span><span><b>{totals.attending}</b> حضور</span><span><b>{totals.guests}</b> ضيوف</span></div></div><div className="saas-card"><div className="card-icon"><UserRound size={19}/></div><h3>الحساب</h3><strong>شراء مرة واحدة</strong><p>لا توجد خطط شهرية أو سنوية.</p></div></section>
 <section className="saas-section"><h3>المنتجات المتاحة</h3><div className="plan-grid">{products.map(p=><div className="plan-card" key={p.id}><div className="plan-top"><span>{p.product_type==='invitation'?'دعوة':'قالب'}</span>{ownedIds.has(p.id)&&<em>مملوك</em>}</div><div className="price">AED {Number(p.price_aed||0)}</div><h3>{p.name}</h3><p>{p.description||'منتج Everly'}</p><ul><li><CheckCircle2 size={15}/> تصميم فاخر</li><li><CheckCircle2 size={15}/> RSVP</li><li><CheckCircle2 size={15}/> مشاركة عبر رابط</li></ul><button className="primary-button" disabled={ownedIds.has(p.id)} onClick={()=>buy(p)}>{ownedIds.has(p.id)?'تم الشراء':user?'شراء المنتج':'تسجيل الدخول للشراء'}</button></div>)}</div>{!user&&<div className="saas-message"><LockKeyhole size={16}/> يمكنك استعراض المنتجات والأسعار بدون حساب. سجّل الدخول عند الشراء.</div>}</section>
 <section className="saas-section"><h3>طلباتي</h3>{user?(orders.length?orders.map(o=><div className="template-row" key={o.id}><span>#{o.id.slice(0,8)}</span><span>AED {Number(o.total_aed||0)}</span><span>{o.status==='paid'?'مدفوع':o.status==='pending'?'بانتظار الدفع':o.status}</span></div>):<p className="muted-note">لا توجد طلبات حتى الآن.</p>):<p className="muted-note">سجّل الدخول لمشاهدة طلباتك.</p>}<p className="muted-note">الطلب يُسجل كـ pending حتى يتم ربط بوابة الدفع. لا يتم اعتبار المنتج مملوكاً قبل تأكيد الدفع.</p></section>
 <section className="saas-section"><h3>بيانات الحساب</h3>{user?<form className="profile-form" onSubmit={saveProfile}><label>الاسم<input value={profile.full_name} onChange={e=>setProfile({...profile,full_name:e.target.value})}/></label><label>الهاتف<input value={profile.phone} onChange={e=>setProfile({...profile,phone:e.target.value})}/></label><label>الدولة<input value={profile.country} onChange={e=>setProfile({...profile,country:e.target.value})}/></label><button className="primary-button" type="submit"><UserRound size={16}/> حفظ البيانات</button></form>:<p className="muted-note">سجّل الدخول لإدارة بيانات حسابك.</p>}</section>
 {loading&&<div className="saas-loading"><RefreshCw size={16}/> جاري تحميل المتجر…</div>}
 </div>
}
