import React,{useEffect,useMemo,useState} from 'react';
import {BarChart3,Crown,Globe,UserRound,CheckCircle2,Clock3,RefreshCw} from 'lucide-react';
import {backendReady,getSession,listPlans,listTemplates,getMySubscription,upsertCustomerProfile,listRsvpAnalytics} from './lib/supabase';

export default function SaaSPanel({invitations=[],onBack}){
 const [plans,setPlans]=useState([]),[templates,setTemplates]=useState([]),[subscription,setSubscription]=useState(null),[analytics,setAnalytics]=useState([]),[profile,setProfile]=useState({full_name:'',phone:'',country:''}),[loading,setLoading]=useState(true),[message,setMessage]=useState('');
 const user=getSession()?.user;
 useEffect(()=>{let live=true;(async()=>{if(!backendReady()){setLoading(false);return;}try{const [p,t,s,a]=await Promise.all([listPlans(),listTemplates(),getMySubscription(),listRsvpAnalytics()]);if(live){setPlans(p||[]);setTemplates(t||[]);setSubscription(s);setAnalytics(a||[]);setProfile(x=>({...x,full_name:user?.user_metadata?.full_name||user?.email?.split('@')[0]||''}));}}catch(e){if(live)setMessage(e.message)}finally{if(live)setLoading(false)}})();return()=>{live=false}},[]);
 const totals=useMemo(()=>analytics.reduce((a,r)=>({responses:a.responses+Number(r.total_responses||0),attending:a.attending+Number(r.attending_responses||0),declined:a.declined+Number(r.declined_responses||0),guests:a.guests+Number(r.attending_guests||0)}),{responses:0,attending:0,declined:0,guests:0}),[analytics]);
 async function saveProfile(e){e.preventDefault();try{await upsertCustomerProfile(profile);setMessage('تم حفظ بيانات الحساب بنجاح.')}catch(e){setMessage(e.message)}}
 return <div className="saas-panel"><div className="saas-head"><div><div className="eyebrow">EVERLY ACCOUNT</div><h2>الحساب والخطة</h2><p>{user?.email||'حساب Everly'}</p></div><button className="ghost-button" onClick={onBack}>رجوع</button></div>
 {message&&<div className="saas-message">{message}</div>}
 <section className="saas-grid"><div className="saas-card"><div className="card-icon"><Crown size={19}/></div><h3>خطتك الحالية</h3><strong>{subscription?.plans?.name||'Free'}</strong><p>{subscription?'اشتراك نشط':'لا يوجد اشتراك مدفوع حالياً'}</p></div><div className="saas-card"><div className="card-icon"><BarChart3 size={19}/></div><h3>إحصائيات RSVP</h3><div className="mini-stats"><span><b>{totals.responses}</b> ردود</span><span><b>{totals.attending}</b> حضور</span><span><b>{totals.guests}</b> ضيوف</span></div></div><div className="saas-card"><div className="card-icon"><Globe size={19}/></div><h3>النطاقات المخصصة</h3><strong>جاهز للإعداد</strong><p>يتطلب ربط DNS والاستضافة قبل التفعيل.</p></div></section>
 <section className="saas-section"><h3>الخطط</h3><div className="plan-grid">{(plans.length?plans:[{name:'Free',price_aed:0,description:'دعوات أساسية'},{name:'Premium',price_aed:49,description:'قوالب ومزايا متقدمة'},{name:'Pro',price_aed:99,description:'نطاق مخصص وهوية متقدمة'}]).map((p,i)=><div className={`plan-card ${i===1?'featured':''}`} key={p.id||p.name}><div className="plan-top"><span>{p.name}</span>{i===1&&<em>الأكثر طلباً</em>}</div><div className="price">AED {Number(p.price_aed||0)}<small>/month</small></div><p>{p.description||'خطة Everly'}</p><ul><li><CheckCircle2 size={15}/> إنشاء دعوات رقمية</li><li><CheckCircle2 size={15}/> RSVP وإدارة الضيوف</li>{i>0&&<li><CheckCircle2 size={15}/> قوالب Premium</li>}{i>1&&<li><CheckCircle2 size={15}/> Custom Domain</li>}</ul><button className="primary-button" onClick={()=>setMessage(p.price_aed?'الدفع الإلكتروني سيتم ربطه في المرحلة التالية.':'أنت على الخطة المجانية.')}>{p.price_aed?'اختيار الخطة':'الخطة الحالية'}</button></div>)}</div></section>
 <section className="saas-section"><h3>بيانات الحساب</h3><form className="profile-form" onSubmit={saveProfile}><label>الاسم<input value={profile.full_name} onChange={e=>setProfile({...profile,full_name:e.target.value})}/></label><label>الهاتف<input value={profile.phone} onChange={e=>setProfile({...profile,phone:e.target.value})}/></label><label>الدولة<input value={profile.country} onChange={e=>setProfile({...profile,country:e.target.value})}/></label><button className="primary-button" type="submit"><UserRound size={16}/> حفظ البيانات</button></form></section>
 <section className="saas-section"><h3>كتالوج القوالب</h3><div className="template-list">{templates.map(t=><div key={t.id} className="template-row"><span>{t.name}</span><span>{t.is_premium?'Premium':'Free'}</span><span>AED {Number(t.price_aed||0)}</span></div>)}</div></section>
 {loading&&<div className="saas-loading"><RefreshCw size={16}/> جاري تحميل بيانات الحساب…</div>}
 </div>
}
