import React,{useEffect,useState} from 'react';
import {createPortal} from 'react-dom';
import {CalendarDays,Car,ExternalLink,Heart,MapPin,Plane,Users} from 'lucide-react';
import {backendReady,getInvitationBySlug} from './lib/supabase';
import './wedding-final-sections.css';

const fmtDate=v=>v?new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'long',year:'numeric'}).format(new Date(`${v}T12:00:00`)):'Date to be announced';

export default function WeddingFinalSections(){
 const [route,setRoute]=useState(window.location.hash),[data,setData]=useState(null),[target,setTarget]=useState(null);
 useEffect(()=>{const h=()=>setRoute(window.location.hash);window.addEventListener('hashchange',h);return()=>window.removeEventListener('hashchange',h)},[]);
 useEffect(()=>{let live=true;const slug=route.startsWith('#invite/')?decodeURIComponent(route.slice(8)):'';setData(null);if(!slug||!backendReady())return;getInvitationBySlug(slug).then(row=>{if(live)setData(row)}).catch(()=>{});return()=>{live=false}},[route]);
 useEffect(()=>{let cancelled=false;const find=()=>{const el=document.querySelector('.j-page main');if(el&&!cancelled)setTarget(el);else if(!cancelled)requestAnimationFrame(find)};find();return()=>{cancelled=true}},[route,data]);
 if(!target||!data||!route.startsWith('#invite/'))return null;
 const groom=data.groom||'Mohamed',bride=data.bride||'Laila',venue=data.venue||'Wedding Venue',address=data.address||'Address to be announced',map=data.map_url;
 const rsvp=data.rsvp_contact;
 return createPortal(<>
   <section className="wf-venue" id="venue">
    <div className="wf-shell"><div className="wf-kicker">THE PLACE TO BEGIN</div><div className="wf-title-row"><div><h2>Meet us at <i>{venue}</i></h2><p className="wf-ar" lang="ar">نلتقيكم في يومنا الكبير، ونتمنى نشوفكم معانا في أجمل لحظاتنا.</p></div><MapPin className="wf-title-icon"/></div>
     <div className="wf-venue-grid"><div className="wf-card wf-main-card"><div className="wf-card-icon"><MapPin size={18}/></div><span className="wf-label">VENUE</span><h3>{venue}</h3><p>{address}</p><div className="wf-actions">{map&&<a href={map} target="_blank" rel="noreferrer"><MapPin size={15}/> Open directions <ExternalLink size={13}/></a>}<a href="#rsvp"><CalendarDays size={15}/> View invitation</a></div></div><div className="wf-card"><div className="wf-card-icon"><Car size={18}/></div><span className="wf-label">PARKING</span><h3>Arrive with ease</h3><p>Parking information will be shared here with the final venue details. Please allow extra time before the ceremony.</p><span className="wf-ar" lang="ar">خلو زمن بسيط للمواقف والوصول قبل بداية المراسم.</span></div></div>
    </div>
   </section>
   <section className="wf-family" id="family"><div className="wf-shell"><div className="wf-kicker">TWO FAMILIES · ONE JOY</div><h2>With the love of our <i>families.</i></h2><p className="wf-lead">A Sudanese wedding is a celebration shared by more than two hearts — it brings families, generations and loved ones together.</p><p className="wf-ar" lang="ar">الفرحة ما بين محمد وليلي بس؛ دي فرحة أهل وعائلات وأجيال كلها مجتمعة.</p><div className="wf-family-grid"><article><Users size={20}/><span>GROOM'S FAMILY</span><strong>Family of {groom}</strong><p>With gratitude for the family who raised, supported and blessed this journey.</p></article><div className="wf-heart"><Heart size={21} fill="currentColor"/></div><article><Users size={20}/><span>BRIDE'S FAMILY</span><strong>Family of {bride}</strong><p>With love for the family who welcomes this new chapter with open hearts.</p></article></div></div></section>
   <section className="wf-travel" id="travel"><div className="wf-shell"><div className="wf-kicker">FOR OUR GUESTS</div><h2>Travel & <i>stay.</i></h2><p className="wf-lead">Coming from another city? Here are a few simple notes to make your visit comfortable.</p><div className="wf-travel-grid"><article><Plane size={20}/><h3>Arriving</h3><p>Plan your journey early and keep the ceremony start time in mind when choosing your arrival.</p><span className="wf-ar" lang="ar">لو جايين من مدينة تانية، رتبوا مشواركم بدري عشان تصلوا مرتاحين.</span></article><article><MapPin size={20}/><h3>Getting around</h3><p>Use the venue map or directions above for the easiest route and allow extra time for parking.</p><span className="wf-ar" lang="ar">استخدموا الخريطة ومعلومات المكان عشان الوصول يكون ساهل.</span></article><article><Heart size={20}/><h3>Stay close</h3><p>Choose accommodation close to the celebration venue whenever possible for a relaxed evening.</p><span className="wf-ar" lang="ar">يفضل السكن قريب من مكان الاحتفال عشان تكون الليلة أهدأ وأجمل.</span></article></div></div></section>
   <section className="wf-final" id="rsvp"><div className="wf-shell"><div className="wf-monogram">{groom[0]} <span>♡</span> {bride[0]}</div><div className="wf-kicker">UNTIL WE CELEBRATE TOGETHER</div><h2>Save the date.<br/><i>Bring your heart.</i></h2><p>{fmtDate(data.wedding_date)}{data.wedding_time?` · ${data.wedding_time}`:''}</p><p className="wf-ar" lang="ar">احفظوا التاريخ وتعالوا شاركونا فرحتنا. وجودكم هو أجمل هدية.</p><div className="wf-final-actions">{rsvp&&<a href={`https://wa.me/${String(rsvp).replace(/\\D/g,'')}?text=${encodeURIComponent(`Hello! I would like to RSVP for ${groom} & ${bride}.`)}`} target="_blank" rel="noreferrer">Confirm by WhatsApp</a>}{map&&<a href={map} target="_blank" rel="noreferrer">Venue directions</a>}</div><div className="wf-footer"><span>Mohamed & Laila</span><span>✦ Sudanese Jertiq ✦</span><span>Made with love</span></div></div></section>
 </>,target);
}
